/* CREATE TABLE TABLE_NAME(
        COLUMN_NAME DATA_TYPE(LENGTH) ,
        ......
    );
*/
DROP TABLE emp_ddl;

CREATE TABLE emp_ddl (
    empno    NUMBER(4),
    ename    VARCHAR2(10),
    job      VARCHAR2(9),
    mgr      NUMBER(4),
    hiredate DATE,
    sal      NUMBER(7, 2),
    com      NUMBER(7, 2),
    deptno   NUMBER(2)
);

DESC EMP_DDL;

DROP TABLE dept_ddl;

CREATE TABLE dept_ddl
    AS
        SELECT
            *
        FROM
            dept;

DESC DEPT_DDL;

CREATE TABLE salgrade_ddl
    AS
        SELECT
            *
        FROM
            salgrade;

DESC SALGRADE_DDL;

/* ALTER TABLE <TABLE_NAME>
    1.ADD <COLNAME> <DATATYPE>;
    2.DROP <COLNAME>;
    3.MODIFY <COLNAME> <DATATYPE>;
    4.RENAME COLUMN <OLD_COLNAME> TO <NEW_COLNAME>
*/
ALTER TABLE salgrade_ddl ADD party VARCHAR2(20);

ALTER TABLE salgrade_ddl RENAME COLUMN party TO home;

ALTER TABLE salgarde_ddl MODIFY
    home NUMBER(10);

DESC SALGRADE_DDL;

ALTER TABLE salgrade_ddl DROP COLUMN home;

RENAME salgrade_ddl TO salzip;

DESC SALZIP;

SELECT
    *
FROM
    salzip;

TRUNCATE TABLE salzip;

DROP TABLE salzip;
/*
COMMENT ON TABLE <TABLE_NAME> IS <COMMENT>;
COMMENT ON COLUMN <TABLE_NAME>.<COLNAME> IS <COMMENT>;
*/
COMMENT ON TABLE dept_ddl IS
    'DDL연습테이블';

COMMENT ON COLUMN depf_ddl.loc IS
    '부서위치';

SELECT
    *
FROM
    user_tab_comments;

SELECT
    *
FROM
    user_col_comments
WHERE
    table_name = 'DEPT_DDL';

/* CONSTRAINT
    NOT NULL/UNIQUE/PRIMARY KEY/FOREIGN KEY/CHECK/DEFAULT
*/
DROP TABLE persons;

DROP TABLE persons2;

CREATE TABLE persons (
    id     VARCHAR2(4) PRIMARY KEY,
    name   VARCHAR2(20) NOT NULL UNIQUE,
    age    NUMBER(3) CHECK ( age >= 18 ),
    telnum VARCHAR2(20),
    addr   VARCHAR2(100) DEFAULT 'SEOUL',
    bday   DATE DEFAULT sysdate
);

INSERT INTO persons (
    id,
    name,
    age,
    telnum
) VALUES (
    '1000',
    'SCOTT',
    20,
    '01012345567'
);

INSERT INTO persons (
    name,
    age,
    telnum
) VALUES (
    'SCOTT',
    20,
    '010123445567'
);

CREATE TABLE persons2 (
    id     VARCHAR2(4),
    name   VARCHAR2(20) NOT NULL,
    age    NUMBER(3),
    telnum VARCHAR2(20),
    addr   VARCHAR2(100) DEFAULT 'SEOUL',
    bday   DATE DEFAULT sysdate,
    CONSTRAINT pk_person2 PRIMARY KEY ( id ),
    CONSTRAINT un_person2 UNIQUE ( name ),
    CONSTRAINT chk_person2 CHECK ( age >= 18 )
);

ALTER TABLE persons2 MODIFY
    addr DEFAULT 'PARIS';

ALTER TABLE persons2 DROP CONSTRAINT chk_person2;

ALTER TABLE persons2 ADD CONSTRAINT chk_p2 CHECK ( age > 50 );

DROP TABLE plays;

CREATE TABLE plays(
    PLAY_ID NUMBER(10) PRIMARY KEY,
    PLAY_RESULT VARCHAR2(100),
    PERSONS_ID VARCHAR2(4), constraint fk_plays FOREIGN KEY(persons_id)
    REFERENCES person(id)
        ON DELETE CASCADE

    ADDR DEFAULT 'PARIS';

ALTER TABLE persons2 DROP CONSTRAINT chk_person2;

ALTER TABLE persons2 ADD CONSTRAINT chk_p2 CHECK ( age > 50 );

DROP TABLE plays;

CREATE TABLE plays(
    PLAY_ID NUMBER(10) PRIMARY KEY,
    PLAY_RESULT VARCHAR2(100),
    PERSONS_ID VARCHAR2(4), constraint fk_plays FOREIGN KEY(persons_id)
    REFERENCES person(id)ON DELETE CASCADE
        );
        --ON DELETE SET NULL
        DROP TABLE FKTABLE;
        DROP TABLE PKTABEL;
        CREATE TABLE PKTABLE(
        PKVAL VARCHAR2(10),
        CONSTRAINT PK_KEY PRIMARY KEY(PKVAL)
        );
        CREATE TABLE FKTABLE(
        PKVAL VARCHAR2(10),
        FKVAL VARCHAR2(10)
        );
ALTER TABLE fktable 
add constraint fk__key foreign key ( fkval ) referances
PKTABLE(PKVAL) ON DELETE CASCADE;

ALETER TABLE FKTABLE ADD CONSTRAINT FKT_PK_KEY PRIMARY KEY(PKVAL);


INSERT INTO PKTABLE VALUES('PK1');
INSERT INTO PKTABLE VALUES('PK2');
INSERT INTO PKTABLE VALUES('PK3');
SELECT * FROM PKTABLE;

INSERT INTO FKTABLE VALUES('PK1-VAL1','PK1');
INSERT INTO FKTABLE VALUES('PK1-VAL2','PK1');
INSERT INTO FKTABLE VALUES('PK2-VAL1','PK2');
INSERT INTO FKTABLE VALUES('PK2-VAL2','PK2');
INSERT INTO FKTABLE VALUES('PK3-VAL1','PK3');
INSERT INTO FKTABLE VALUES('PK3-VAL2','PK3');
SELECT * FROM FKTABLE;

DELETE FROM PKTABLE WHERE PKVAL='PK1';
SELECT * FROM PKTABLE;
SELECT * FROM FKTABLE;

--Q1 EMP_HW TABLE 생성
DROP TABLE EMP_HW;
CREATE TABLE EMP_HW(
   empno NUMBER(4,0),
   ename varchar2(10),
   job varchar2(9),
   mgr number(4,0),
   hiredate DATE,
   sal number(7,2),
   comm number(7,2),
   deptno number(2,0),
   CONSTRAINT HW_PK_EMP  PRIMARY KEY(empno),
   CONSTRAINT HW_FK_DEPTNO FOREIGN KEY(DEPTNO)
   REFERENCES DEPT(DEPTNO)
);
--Q2 EMP_HW 컬럼 BIGO 추가 VARCHAR2(20)
DESC EMP_HW;
ALTER TABLE EMP_HW ADD BIGO VARCHAR2(20);
--Q3 BIGO 컬럼의 타입 VARCHAR2(40)
ALTER TABLE EMP_HW MODIFY BIGO VARCHAR2(40);
--Q4 BIGO 컬럼의 이름을 REMARK로 변경
ALTER TABLE EMP_HW RENAME COLUMN BIGO TO REMARK;
--Q5 EMP_HW 테이블 삭제
DROP TABLE EMP_HW;

basic.sql
/*CREATE TABLE TABLE_NAME(
        COLUMN_NAME DATA_TYPE(LENGTH),
        ......
    );
*/
DROP TABLE EMP_DDL;
CREATE TABLE EMP_DDL(
    EMPNO NUMBER(4),
    ENAME VARCHAR2(10),
    JOB VARCHAR2(9),
    MGR NUMBER(4),
    HIREDATE DATE,
    SAL NUMBER(7,2),
    COMM NUMBER(7,2),
    DEPTNO NUMBER(2)
);
DESC EMP_DDL;
DROP TABLE DEPT_DDL;
CREATE TABLE DEPT_DDL
AS SELECT * FROM DEPT;
DESC DEPT_DDL;
DROP TABLE SALGRADE_DDL;
CREATE TABLE SALGRADE_DDL
AS SELECT * FROM SALGRADE;
DESC SALGRADE_DDL;

/* ALTER TABLE <TABLE_NAME>
    1.ADD <COLNAME> <DATATYPE>;
    2.DROP <COLNAME>;
    3.MODIFY <COLNAME> <DATATYPE>;
    4.RENAME COLUMN <OLD_COLNAME> TO <NEW_COLNAME>
*/
ALTER TABLE SALGRADE_DDL
ADD PARTY VARCHAR2(20);

ALTER TABLE SALGRADE_DDL
RENAME COLUMN PARTY TO HOME;

ALTER TABLE SALGRADE_DDL
MODIFY HOME NUMBER(10);
DESC SALGRADE_DDL;

ALTER TABLE SALGRADE_DDL
DROP COLUMN HOME;

RENAME SALGRADE_DDL TO SALZIP;

DESC SALZIP;
SELECT * FROM SALZIP;

TRUNCATE TABLE SALZIP;
DROP TABLE SALZIP;

/*
COMMENT ON TABLE <TABLE_NAME> IS <COMMENT>;
COMMENT ON COLUMN <TABLE_NAME>.<COLNAME> IS <COMMENT>;
*/
COMMENT ON TABLE DEPT_DDL IS 'DDL연습테이블';
COMMENT ON COLUMN DEPT_DDL.LOC IS '부서위치';

SELECT * FROM USER_TAB_COMMENTS;
SELECT * FROM USER_COL_COMMENTS WHERE TABLE_NAME='DEPT_DDL';

/* CONSTRAINT
    NOT NULL/UNIQUE/PRIMARY KEY/FOREIGN KEY/CHECK/DEFAULT
*/
DROP TABLE PERSONS;
DROP TABLE PERSONS2;

CREATE TABLE PERSONS(
    ID VARCHAR2(4) PRIMARY KEY,
    NAME VARCHAR2(20) NOT NULL UNIQUE,
    AGE NUMBER(3) CHECK(AGE>=18),
    TELNUM VARCHAR2(20),
    ADDR VARCHAR2(100) DEFAULT 'SEOUL',
    BDAY DATE DEFAULT SYSDATE
);
INSERT INTO PERSONS(ID,NAME,AGE,TELNUM)
VALUES('1001','SCOTT',20,'010123445567');
INSERT INTO PERSONS(NAME,AGE,TELNUM)
VALUES('SCOTT',20,'010123445567');

CREATE TABLE PERSONS2(
    ID VARCHAR2(4),
    NAME VARCHAR2(20) NOT NULL,
    AGE NUMBER(3),
    TELNUM VARCHAR2(20),
    ADDR VARCHAR2(100) DEFAULT 'SEOUL',
    BDAY DATE DEFAULT SYSDATE,
    CONSTRAINT PK_PERSON2 PRIMARY KEY(ID),
    CONSTRAINT UN_PERSON2 UNIQUE(NAME),
    CONSTRAINT CHK_PERSON2 CHECK(AGE>=18)
);
ALTER TABLE PERSONS2
MODIFY ADDR DEFAULT 'PARIS';

ALTER TABLE PERSONS2
DROP CONSTRAINT CHK_PERSON2;

ALTER TABLE PERSONS2
ADD CONSTRAINT CHK_P2 CHECK(AGE>50);

DROP TABLE PLAYS;
CREATE TABLE PLAYS(
    PLAY_ID NUMBER(10) PRIMARY KEY,
    PLAY_RESULT VARCHAR2(100),
    PERSONS_ID VARCHAR2(4),
    CONSTRAINT FK_PLAYS FOREIGN KEY(PERSONS_ID)
    REFERENCES PERSONS(ID) ON DELETE CASCADE
);
--ON DELETE SET NULL
DROP TABLE FKTABLE;
DROP TABLE PKTABLE;
CREATE TABLE PKTABLE(
    PKVAL VARCHAR2(10),
    CONSTRAINT PK_KEY PRIMARY KEY(PKVAL)
);
CREATE TABLE FKTABLE(
    PKVAL VARCHAR2(10),
    FKVAL VARCHAR2(10)
);
ALTER TABLE FKTABLE
ADD CONSTRAINT FK_KEY FOREIGN KEY(FKVAL) REFERENCES PKTABLE(PKVAL)
ON DELETE CASCADE;
ALTER TABLE FKTABLE
ADD CONSTRAINT FKT_PK_KEY PRIMARY KEY(PKVAL);

INSERT INTO PKTABLE VALUES('PK1');
INSERT INTO PKTABLE VALUES('PK2');
INSERT INTO PKTABLE VALUES('PK3');
SELECT * FROM PKTABLE;

INSERT INTO FKTABLE VALUES('PK1-VAL1','PK1');
INSERT INTO FKTABLE VALUES('PK1-VAL2','PK1');
INSERT INTO FKTABLE VALUES('PK2-VAL1','PK2');
INSERT INTO FKTABLE VALUES('PK2-VAL2','PK2');
INSERT INTO FKTABLE VALUES('PK3-VAL1','PK3');
INSERT INTO FKTABLE VALUES('PK3-VAL2','PK3');
SELECT * FROM FKTABLE;

DELETE FROM PKTABLE WHERE PKVAL='PK1';
SELECT * FROM PKTABLE;
SELECT * FROM FKTABLE;
--Q1 EMP_HW TABLE 생성
CREATE TABLE EMP_HW(
    EMPNO NUMBER(4),
    ENAME VARCHAR2(10),
    JOB VARCHAR2(9),
    MGR NUMBER(4),
    HIREDATE DATE,
    SAL NUMBER(7,2),
    COMM NUMBER(7,2),
    DEPTNO NUMBER(2),
    CONSTRAINT HW_PK_EMP PRIMARY KEY(EMPNO),
    CONSTRAINT HW_FK_DEPTNO FOREIGN KEY(DEPTNO) 
    REFERENCES DEPT(DEPTNO)
);
--Q2 EMP_HW 컬럼 BIGO 추가 VARCHAR2(20)
ALTER TABLE EMP_HW
ADD BIGO VARCHAR2(20);
--Q3 BIGO 컬럼의 타입 VARCHAR2(40)
ALTER TABLE EMP_HW
MODIFY BIGO VARCHAR2(40);
DESC EMP_HW;
--Q4 BIGO 컬럼의 이름을 REMARK로 변경
ALTER TABLE EMP_HW
RENAME COLUMN BIGO TO REMARK;
--Q5 EMP_HW 테이블 삭제
DROP TABLE EMP_HW;



