DROP TABLE MEMBER;

CREATE TABLE MEMBER (
ID VARCHAR2(10) PRIMARY KEY,
PW VARCHAR2(10) NOT NULL ,
NAME VARCHAR2(30) NOT NULL , 
REGDATE DATE DEFAULT SYSDATE NOT NULL
);

DROP TABLE BOARD;

CREATE TABLE BOARD(
   NUM NUMBER PRIMARY KEY,
   TITLE VARCHAR2(200) NOT NULL,
   CONTENT VARCHAR2(2000) NOT NULL,
   ID VARCHAR2(10) NOT NULL,
   POSDATE DATE DEFAULT SYSDATE NOT NULL,
   VISITCOUNT NUMBER(6,0)
   --,CONSTRAINT FK_ID FOREIGN KEY(ID) REFERENCES MEMBER(ID)
);

ALTER TABLE BOARD
ADD CONSTRAINT BOARD_NUM_FK FOREIGN KEY(ID) REFERENCES MEMBER(ID);

--1에서 시작 1씩 증가 최소값 1 최대값은 무한대 순환없고 캐쉬안하고
DROP SEQUENCE SEQ_BOARD_NUM;
CREATE SEQUENCE SEQ_BOARD_NUM
INCREMENT BY 1
START WITH 1
MINVALUE 1
NOMAXVALUE
NOCYCLE
NOCACHE;


INSERT INTO MEMBER(ID,PW,NAME)VALUES('admin','1234','관리자'); 
INSERT INTO MEMBER(ID,PW,NAME)VALUES('SIBAL','NOM','시발롬'); 
INSERT INTO MEMBER(ID,PW,NAME)VALUES('JA','VA','자바'); 
INSERT INTO MEMBER(ID,PW,NAME)VALUES('O','RACLE','오라클'); 


INSERT INTO BOARD(NUM,TITLE,CONTENT,ID,VISITCOUNT) 
VALUES(SEQ_BOARD_NUM.NEXTVAL, '더미제목1','더미내용1','JA',0);
COMMIT;

DROP TABLE FILEBOARD;
CREATE TABLE FILEBOARD (
   IDX NUMBER NOT NULL,
   NAME VARCHAR2(50) NOT NULL,
   TITLE VARCHAR2(200) NOT NULL,
   CONTENT VARCHAR2(2000) NOT NULL,
   POSTDATE DATE DEFAULT SYSDATE NOT NULL,
   OFILE VARCHAR2(200) NULL,
   NFILE VARCHAR2(100) NULL,
   DOWNCOUNT NUMBER(5,0) DEFAULT 0 NOT NULL,
   VISITCOUNT NUMBER DEFAULT 0 NOT NULL,
   PASS VARCHAR2(50) NOT NULL,
   CONSTRAINT FILEBOARD_PK PRIMARY KEY (IDX)
);

INSERT INTO FILEBOARD(IDX,NAME,TITLE,CONTENT,PASS)
VALUES(SEQ_BOARD_NUM.NEXTVAL,'강감찬','자료게시판','더미내용','1234');

INSERT INTO FILEBOARD(IDX,NAME,TITLE,CONTENT,PASS)
VALUES(SEQ_BOARD_NUM.NEXTVAL,'을지문덕','자료게시판2','더미내용2','1234');
INSERT INTO FILEBOARD(IDX,NAME,TITLE,CONTENT,PASS)
VALUES(SEQ_BOARD_NUM.NEXTVAL,'계백','자료게시판3','더미내용3','1234');

SELECT * FROM (SELECT ROWNUM PNUM, S.* FROM(SELECT B.* FROM FILEBOARD B 
WHERE LIKE '%내%' ORDER BY NUM DESC) S) WHERE PNUM BETWEEN ? AND ?;

SELECT * FROM FILEBOARD;


        SELECT *
      FROM(
        SELECT ROWNUM AS PNUM,S.*
        FROM(
            SELECT *
            FROM FILEBOARD
            WHERE TITLE LIKE '%자%'
            ORDER BY IDX DESC
        )S
    )WHERE PNUM BETWEEN 1 AND 2;
