DROP TABLE MYFILE;
CREATE TABLE MYFILE ( 
IDX NUMBER  PRIMARY KEY,
NAME VARCHAR2(50) NOT NULL,
TITLE VARCHAR2(200) NOT NULL,
CATE VARCHAR2(100) ,
OFILE VARCHAR2(200) NOT NULL,
NFILE VARCHAR2(100) NOT NULL,
REGDATE DATE DEFAULT SYSDATE NOT NULL);