DROP TABLE ORG;
CREATE TABLE ORG(
ORGCODE VARCHAR2(50) NOT NULL ,
ORGNAME VARCHAR2(50) NOT NULL,
ORGLEVEL VARCHAR(50) NOT NULL,
ORGUPPERCODE VARCHAR2(50) NOT NULL
);

INSERT INTO ORG (ORGCODE, ORGLEVEL, ORGNAME, ORGUPPERCODE)
VALUES ('01000000', 1, 'REBOOT', '00000000');

INSERT INTO ORG (ORGCODE, ORGLEVEL, ORGNAME, ORGUPPERCODE)
SELECT '0' || TO_CHAR(ROWNUM + 1, 'FM00') || '000000', 2, DEPTN, '01000000'
FROM (
    SELECT DISTINCT DEPTN
    FROM INFO
    ORDER BY DEPTN
);

INSERT INTO ORG (ORGCODE, ORGLEVEL, ORGNAME, ORGUPPERCODE)
SELECT '0' || SUBSTR(ORGCODE, 2, 2) || TO_CHAR(GRADE, 'FM00') || '0000', 3, DECODE(GRADE, 1, '팀장', '팀원'), ORGCODE
FROM (
    SELECT DISTINCT DEPTN, GRADE, ORGCODE
    FROM INFO
    JOIN ORG ON INFO.DEPTN = ORG.ORGNAME
    WHERE ORGLEVEL = 2
);

INSERT INTO ORG (ORGCODE, ORGLEVEL, ORGNAME, ORGUPPERCODE)
SELECT '0' || SUBSTR(PARENT.ORGCODE, 2, 4) || TO_CHAR(ROWNUM, 'FM00') || '00', 4, INFO.NAME, PARENT.ORGCODE
FROM INFO
JOIN ORG PARENT ON INFO.DEPTN = PARENT.ORGNAME AND DECODE(INFO.GRADE, 1, '팀장', '팀원') = PARENT.ORGNAME
WHERE PARENT.ORGLEVEL = 3
ORDER BY INFO.DEPTN, INFO.GRADE, INFO.NAME;

INSERT INTO ORG (ORGCODE, ORGLEVEL, ORGNAME, ORGUPPERCODE)
SELECT '0' || SUBSTR(PARENT.ORGCODE, 2, 4) || LPAD(ROWNUM, 2, '0') || '00', 4, INFO.NAME, PARENT.ORGCODE
FROM INFO
JOIN ORG PARENT ON INFO.DEPTN = PARENT.ORGNAME AND DECODE(INFO.GRADE, 1, '팀장', '팀원') = PARENT.ORGNAME
WHERE PARENT.ORGLEVEL = 3
ORDER BY INFO.DEPTN, INFO.GRADE, INFO.NAME;

INSERT INTO ORG (ORGCODE, ORGLEVEL, ORGNAME, ORGUPPERCODE)
SELECT '0' || SUBSTR(PARENT.ORGCODE, 2, 4) || LPAD(ROWNUM, 2, '0') || '00', 4, INFO.NAME, PARENT.ORGCODE
FROM INFO
JOIN ORG PARENT ON INFO.DEPTN = PARENT.ORGNAME AND DECODE(INFO.GRADE, 1, '팀장', '팀원') = PARENT.ORGNAME
WHERE PARENT.ORGLEVEL = 3
ORDER BY INFO.DEPTN, INFO.GRADE, INFO.NAME;

INSERT INTO ORG (ORGCODE, ORGLEVEL, ORGNAME, ORGUPPERCODE)
SELECT '0' || SUBSTR(PARENT.ORGCODE, 2, 4) || LPAD(ROWNUM, 2, '0') || '00', 4, INFO.NAME, PARENT.ORGCODE
FROM INFO
JOIN ORG PARENT ON INFO.DEPTN = PARENT.ORGNAME AND DECODE(INFO.GRADE, 1, 1, 2) = PARENT.ORGLEVEL - 1
WHERE PARENT.ORGLEVEL = 3
ORDER BY INFO.DEPTN, INFO.GRADE, INFO.NAME;




WITH INFO_WITH_ROLE AS (
    SELECT ID, NAME, DEPTN, GRADE, 
           CASE
               WHEN GRADE = 1 THEN '팀장'
               ELSE '팀원'
           END AS ROLE
    FROM INFO
)
SELECT ID FROM INFO;
-- 사장 추가
INSERT INTO ORG (ORGCODE, ORGLEVEL, ORGNAME, ORGUPPERCODE)
VALUES ('01000000', 1, 'Reboot', '');

-- 부서명 추가
INSERT INTO ORG (ORGCODE, ORGLEVEL, ORGNAME, ORGUPPERCODE)
SELECT '0' || TO_CHAR(ROW_NUMBER() OVER (ORDER BY DEPT)) || '000000', 2, DEPT, '01000000'
FROM (SELECT DISTINCT DEPT FROM INFO) ORDER BY DEPT;

-- GRADE 추가
INSERT INTO ORG (ORGCODE, ORGLEVEL, ORGNAME, ORGUPPERCODE)
SELECT '0' || SUBSTR(PARENT.ORGCODE, 2, 4) || '0' || DECODE(INFO.ROLE, '팀장', '1', '2') || '0000', 3, INFO.ROLE, PARENT.ORGCODE
FROM (SELECT DISTINCT DEPT, ROLE FROM INFO_WITH_ROLE) INFO
JOIN ORG PARENT ON INFO.DEPT = PARENT.ORGNAME
WHERE PARENT.ORGLEVEL = 2;

-- NAME 추가
INSERT INTO ORG (ORGCODE, ORGLEVEL, ORGNAME, ORGUPPERCODE)
SELECT '0' || SUBSTR(PARENT.ORGCODE, 2, 4) || TO_CHAR(ROW_NUMBER() OVER (PARTITION BY PARENT.ORGCODE ORDER BY INFO.NAME)) || '00', 4, INFO.NAME, PARENT.ORGCODE
FROM INFO_WITH_ROLE INFO
JOIN ORG PARENT ON INFO.DEPT = PARENT.ORGNAME AND INFO.ROLE = PARENT.ORGNAME
WHERE PARENT.ORGLEVEL = 3
ORDER BY INFO.DEPT, INFO.GRADE, INFO.NAME;


-- 사장 추가
INSERT INTO ORG (ORGCODE, ORGLEVEL, ORGNAME, ORGUPPERCODE)
VALUES ('01000000', 1, 'Reboot', '00000000');

-- 부서명 추가
INSERT INTO ORG (ORGCODE, ORGLEVEL, ORGNAME, ORGUPPERCODE)
SELECT '0' || TO_CHAR(ROW_NUMBER() OVER (ORDER BY DEPTN)) || '000000', 2, TO_CHAR(DEPTN), '01000000'
FROM (SELECT DISTINCT DEPTN FROM INFO) ORDER BY DEPTN;

-- GRADE 추가
INSERT INTO ORG (ORGCODE, ORGLEVEL, ORGNAME, ORGUPPERCODE)
SELECT '0' || SUBSTR(PARENT.ORGCODE, 2, 4) || '0' || DECODE(INFO.GRADE, 1, '1', '2') || '0000', 3, 
       CASE
           WHEN INFO.GRADE = 1 THEN '팀장'
           ELSE '팀원'
       END, PARENT.ORGCODE
FROM (SELECT DISTINCT DEPTN, GRADE FROM INFO) INFO
JOIN ORG PARENT ON PARENT.ORGLEVEL = 2 AND PARENT.ORGNAME = TO_CHAR(INFO.DEPTN);

-- NAME 추가
INSERT INTO ORG (ORGCODE, ORGLEVEL, ORGNAME, ORGUPPERCODE)
SELECT '0' || SUBSTR(PARENT.ORGCODE, 2, 4) || '0' || DECODE(INFO.GRADE, 1, '1', '2') || LPAD(ROW_NUMBER() OVER (PARTITION BY INFO.DEPTN, INFO.GRADE ORDER BY INFO.ID), 4, '0'), 4, INFO.NAME, PARENT.ORGCODE
FROM INFO
JOIN ORG PARENT ON PARENT.ORGLEVEL = 3 AND PARENT.ORGNAME = (CASE WHEN INFO.GRADE = 1 THEN '팀장' ELSE '팀원' END) AND PARENT.ORGUPPERCODE = '0' || TO_CHAR(INFO.DEPTN) || '000000';