/* 사용자를 생성
    CREATE USER [USER NAME] IDENTIFIED BY [PASSWORD]
*/
CREATE USER STU IDENTIFIED BY 1234; --아이디생성
ALTER USER STU IDENTIFIED BY 1234; --비번변경
DROP USER STU;

GRANT CREATE SESSION TO STU; --세션권한주기

GRANT SELECT ON SCOTT.SAL_DML TO STU; --셀렉가능권한
GRANT INSERT ON SCOTT.SAL_DML TO STU; --인서트가능권한

REVOKE SELECT,INSERT ON SCOTT.SAL_DML FROM STU;

SELECT * FROM USER_SYS_PRIVS;

CREATE ROLE 반장; --권한뭉탱이
GRANT CONNECT,RESOURCE,CREATE VIEW TO 반장; --스쿨이라는 권한에 커넷트 리소스 크리에티트 가능을 넣음

GRANT 반장 TO STU; --STU에 SCHOOL이라는 권한뭉탱이를 넣음

SELECT * FROM DBA_SYS_PRIVS WHERE GRANTEE='반장';