DROP TABLE MEMBER;

CREATE TABLE MEMBER (
ID VARCHAR2(10) PRIMARY KEY,
PW VARCHAR2(10) NOT NULL ,
NAME VARCHAR2(30) NOT NULL , 
REGDATE DATE DEFAULT SYSDATE NOT NULL
);

DROP TABLE BOARD;

CREATE TABLE BOARD(
   NUM NUMBER PRIMARY KEY,
   TITLE VARCHAR2(200) NOT NULL,
   CONTENT VARCHAR2(2000) NOT NULL,
   ID VARCHAR2(10) NOT NULL,
   POSDATE DATE DEFAULT SYSDATE NOT NULL,
   VISITCOUNT NUMBER(6,0)
   --,CONSTRAINT FK_ID FOREIGN KEY(ID) REFERENCES MEMBER(ID)
);

ALTER TABLE BOARD
ADD CONSTRAINT BOARD_NUM_FK FOREIGN KEY(ID) REFERENCES MEMBER(ID);

--1에서 시작 1씩 증가 최소값 1 최대값은 무한대 순환없고 캐쉬안하고
DROP SEQUENCE SEQ_BOARD_NUM;
CREATE SEQUENCE SEQ_BOARD_NUM
INCREMENT BY 1
START WITH 1
MINVALUE 1
NOMAXVALUE
NOCYCLE
NOCACHE;

INSERT INTO MEMBER(ID,PW,NAME)VALUES('SIBAL','NOM','시발롬'); 
INSERT INTO MEMBER(ID,PW,NAME)VALUES('JA','VA','자바'); 
INSERT INTO MEMBER(ID,PW,NAME)VALUES('O','RACLE','오라클'); 


INSERT INTO BOARD(NUM,TITLE,CONTENT,ID,VISITCOUNT) 
VALUES(SEQ_BOARD_NUM.NEXTVAL, '더미제목1','더미내용1','JA',0);
COMMIT;