SELECT * FROM (SELECT * FROM BOARD ORDER BY NUM DESC) row_num WHERE ROWNUM<=10;

SELECT * FROM(SELECT ROW_NUMBER() OVER(ORDER BY BOARD.NUM) 
row_num, BOARD.* FROM BOARD ORDER BY BOARD.NUM DESC) WHERE row_num<=10;

SELECT ROWNUM,B.* FROM BOARD B WHERE TITLE LIKE '%10%' ORDER BY NUM DESC;

SELECT * FROM(SELECT ROWNUM,BOARD.* FROM BOARD ORDER BY NUM DESC) WHERE ROWNUM/10=1;

SELECT rownum,b.* FROM board b WHERE rownum<=10 ORDER BY num desc;

SELECT * FROM ( SELECT ROWNUM PNUM,S.* FROM(SELECT B.* FROM BOARD B ORDER BY NUM DESC) S ) WHERE PNUM BETWEEN 3 AND 50;

SELECT * FROM ( SELECT ROW_NUMBER() OVER(ORDER BY NUM DESC) 
PNUM , B.* FROM BOARD B WHERE TITLE LIKE '%페이징%' ORDER BY NUM DESC) WHERE PNUM BETWEEN 1 AND 20 ;